### ISSUE TITLE
How to use this plugin for apisix

### ISSUE THREAD

**Issue by fatihbm** [ligreman/kong-proxy-cache-redis-cluster-plugin#1]
Hi, I use apisix for api gateway. This is same like kong. Your project solve distributed cache problem and this is cool. I wonder can I fork this project for apisix. Sorry about that but I haven't experience for lua. May you can share I need know tricks.

**Comment by juzhiyuan** [comment]
Hi @fatihbm, may I know if your question has been resolved?

**Comment by fatihbm** [comment]
In the last few months, I have improved my lua skills.  Inspired by this project, I developed a different plugin.  Now I will try to make it more functional.
